### ISSUE TITLE
Running the front end mobile

### ISSUE THREAD

**Issue by joshleetufts** [jumbocodefall2017/PeopleMakingADifference#7]
Get the following error while running http://localhost:8100/ on the browser:

Error
Close
Runtime Error
Uncaught (in promise): TypeError: Failed to fetch TypeError: Failed to fetch
Stack
Error: Uncaught (in promise): TypeError: Failed to fetch
TypeError: Failed to fetch
    at c (http://localhost:8100/build/polyfills.js:3:19132)
    at c (http://localhost:8100/build/polyfills.js:3:18841)
    at http://localhost:8100/build/polyfills.js:3:19613
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15040)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4238:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:14961)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10214)
    at o (http://localhost:8100/build/polyfills.js:3:7274)
    at <anonymous>
Ionic Framework: 3.7.1
Ionic App Scripts: 3.0.0
Angular Core: 4.4.3
Angular Compiler CLI: 4.4.3
Node: 6.9.2
OS Platform: OS X El Capitan
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by Fripplebubby** [comment]
Access-control-allow-origin i.e. CORS ;)
